analytics_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: ep-empty-sky-a9a996ke-pooler.gwc.azure.neon.tech
      port: 5432
      user: neondb_owner
      password: npg_35XuDGUeAfHV
      dbname: neondb
      schema: analytics
      threads: 4
      sslmode: require
